### ISSUE TITLE
add trajectory of solution points to output.hist

### ISSUE THREAD

**Issue by desktoop** [MATPOWER/mips#4]
in docs, i found the usage:
`[x, f, exitflag, output, lambda] = mips(problem)`

the sturct `output`  has some related information, but it seems i can't found any variables which store the trajectories of all the points in each iterations.

**Comment by rdzman** [comment]
Thanks for bringing this up. Unfortunately, MIPS does not currently have the option to return the trajectory of solution points.

I am tagging this as a feature request. If you want to modify your own copy of `mips.m` in the meantime, it should be quite simple to add it as another field in the lines that assign a `struct` to an element of `hist` (i.e. lines [317-319](https://github.com/MATPOWER/mips/blob/404b026f88b4e5efa65f1255598b1760ec22bb6a/lib/mips.m#L317-L319), [409-411](https://github.com/MATPOWER/mips/blob/404b026f88b4e5efa65f1255598b1760ec22bb6a/lib/mips.m#L409-L411), and [610-613](https://github.com/MATPOWER/mips/blob/404b026f88b4e5efa65f1255598b1760ec22bb6a/lib/mips.m#L610-L613)).

For performance reasons, I think in the official version I may add some options to control whether or not it collects these trajectories.

I welcome your thoughts and suggestions.

**Comment by rdzman** [comment]
We may also want to optionally include trajectories of dual variables and/or other quantities.

**Comment by rdzman** [comment]
I'm going to leave this open as a reminder of the feature request.

**Comment by rdzman** [comment]
Implemented in #7.
