### ISSUE TITLE
solving dc-opf by mips in matlab

### ISSUE THREAD

**Issue by desktoop** [MATPOWER/mips#5]
I am trying to solve AC & DC OPF problems by mips in both matlab and octave. But for DC-OPF, it doesn't work in matlab. 
Here is my code:
```
define_constants;
mpc = loadcase("case30");
mpopt = mpoption("opf.ac.solver", "MIPS");
results = rundcopf(mpc, mpopt);
```

And here is what I get:
```
MATPOWER Version 7.1, 08-Oct-2020 -- DC Optimal Power Flow
Error using  == 
Comparison between double and string is not supported.

Error in mpopt2qpopt (line 72)
    case {'DEFAULT', 0}

Error in dcopf_solver (line 71)
opt = mpopt2qpopt(mpopt, model);

Error in opf_execute (line 54)
    [results, success, raw] = dcopf_solver(om, mpopt);

Error in opf (line 232)
    [results, success, raw] = opf_execute(om, mpopt);

Error in runopf (line 75)
[r, success] = opf(casedata, mpopt);

Error in rundcopf (line 73)
[varargout{1:nargout}] = runopf(casedata, mpopt, fname, solvedcase);
```

My matlab version: R2012a (windows 10)

And by the way, mips works well in octave.

**Comment by rdzman** [comment]
In MATLAB there is a difference between double and single quotes. Double quotes creates a string data type (which didn't exist when MATPOWER was initially developed) and single quotes creates a character array. MATPOWER expects the latter. Also, you want to use `'opf.dc.solver'` for the DC OPF.

So, give this a try ...
```
define_constants;
mpc = loadcase('case30');
mpopt = mpoption('opf.dc.solver', 'MIPS');
results = rundcopf(mpc, mpopt);
```

I will also mention that MIPS is not great at solving LP's, so you'll probably want to find a better solver if you plan to do much DC OPF work.

**Comment by desktoop** [comment]
I'm sorry to bother you again that I made a mistake here. `mpopt = mpoption('opf.dc.solver', 'MIPS');`, that's exactly what i'm using. And there is no exception raised when I was using `mpopt = mpoption("opf.ac.solver", "MIPS");`. I should have check my issue carefully.

I'll try to use other solvers but now i prefer MIPS because I am not good at matlab and MIPS could return the solutions' trajectories easily (#4 your answer helps me a lot, thank you so much😀). Could you give me some advise that if there is any other solvers could return trajectory information?

**Comment by rdzman** [comment]
I am not aware of any, but I can't say I've ever looked for that capability. I'm afraid you'd have to look through the documentation for each to be sure.

I suspect very few people care about the trajectories, especially for solvers that do not guarantee the trajectory lies in the feasible region, as long is the solution is feasible and optimal (and quick).
